--- #YAML:1.0
name:               CACertOrg-CA
version:            20110724.001
abstract:           CACert.org's CA root certificate in PEM format
author:
    - brian d foy <bdfoy@cpan.org>
license:            mozilla_1_1 gpl-2 lgpl_2_1
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  http://github.com/briandfoy/cacertorg-ca
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
