---
abstract: "CACert.org's CA root certificate in PEM format"
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CACertOrg-CA
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/briandfoy/cacertorg-ca
version: 20110724.004
